name: Check PR for Screenshot or Video

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  check-pr-content:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR for image or video
        id: check-content
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "PR Body: $PR_BODY"

          imageRegex="!\[.*\]\(.*\)|<img .*src=.*>"
          videoRegex="(https?:\/\/.*\.(?:mp4|mov|avi|wmv|flv|mkv|webm|ogg)|<video .*src=.*)"

          if [[ -z "${PR_BODY// }" || ! "$PR_BODY" =~ $imageRegex && ! "$PR_BODY" =~ $videoRegex ]]; then
            echo "::set-output name=status::failure"
            echo "::set-output name=message::Please include a screenshot or video in the PR description."
            exit 1  # Exit with failure code
          else
            echo "::set-output name=status::success"
            echo "::set-output name=message::PR includes a screenshot or video in the description."
            exit 0  # Exit with success code
          fi

      - name: Set outputs
        id: set-outputs
        run: |
          echo "Status: ${{ steps.check-content.outputs.status }}"
          echo "Message: ${{ steps.check-content.outputs.message }}"
          echo "STATUS=${{ steps.check-content.outputs.status }}" >> $GITHUB_ENV
          echo "MESSAGE=${{ steps.check-content.outputs.message }}" >> $GITHUB_ENV

      - name: Echo status
        if: always()
        run: |
          echo "Status: ${{ steps.check-content.outputs.status }}"
          echo "Message: ${{ steps.check-content.outputs.message }}"

