name: Check Pull Request Flags

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_flags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if YES or NO is checked
        run: |
          # Safely handle multiline and special characters
          body=$(echo "${{ github.event.pull_request.body }}" | tr -d '\r')
          echo "Pull request body:"
          echo "$body"
          # Check for checked YES or NO checkboxes
          if echo "$body" | grep -iq '\[\s*[xX]\s*\]\s*YES'; then
            echo "YES is checked."
            exit 0
          elif echo "$body" | grep -iq '\[\s*[xX]\s*\]\s*NO'; then
            echo "NO is checked."
            exit 0
          else
            echo "Neither YES nor NO checkbox is checked."
            exit 1
          fi
        shell: bash
