name: Check PR for Screenshot or Video

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, labeled, unlabeled]

jobs:
  check-pr-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for Smartling label
        id: check-labels
        env:
          PR_LABELS: ${{ toJSON(github.event.pull_request.labels) }}
        run: |
          echo "Debug: PR Labels: $PR_LABELS"

          LABEL_FOUND=$(echo "$PR_LABELS" | grep -o '"name": "smartling"' | awk -F': ' '{print $2}' | sed 's/"//g')
          echo "Debug: LABEL_FOUND: $LABEL_FOUND"
          
          if [ "$LABEL_FOUND" == "smartling" ]; then
            echo "status=success" >> $GITHUB_ENV
            echo "message=Skipped image or video check due to 'smartling' label." >> $GITHUB_ENV
            exit 0
          fi

      - name: Check PR for image or video
        id: check-content
        if: env.status == 'continue'
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "Debug: PR Body: '$PR_BODY'"

          imageRegex="!\\[.*\\]\\(.*\\)|<img .*src=.*>"
          videoRegex="https?://.*\\.(mp4|mov|avi|wmv|flv|mkv|webm|ogg)|<video .*src=.*>"

          if [[ -z "${PR_BODY// }" ]]; then
            echo "status=failure" >> $GITHUB_ENV
            echo "message=PR body is empty. Please include a screenshot or video in the PR description." >> $GITHUB_ENV
          elif ! echo "$PR_BODY" | grep -qE "$imageRegex" && ! echo "$PR_BODY" | grep -qE "$videoRegex"; then
            echo "status=failure" >> $GITHUB_ENV
            echo "message=Please include a screenshot or video in the PR description." >> $GITHUB_ENV
          else
            echo "status=success" >> $GITHUB_ENV
            echo "message=PR includes a screenshot or video in the description." >> $GITHUB_ENV
          fi

      - name: Echo status
        if: always()
        run: |
          echo "Status: ${{ env.status }}"
          echo "Message: ${{ env.message }}"
          if [[ "${{ env.status }}" == "success" ]]; then
            exit 0
          else
            exit 1
          fi
