name: Check PR for Screenshot or Video

on:
  pull_request:
    branches: '**'  # Apply to pull requests targeting any branch
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  check-pr-content:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR for image or video
      id: pr-check
      uses: actions/github-script@v6
      with:
        script: |
          const prBody = context.payload.pull_request.body;

          const imageRegex = /!\[.*\]\(.*\)|<img .*src=.*>/; // Markdown or HTML image
          const videoRegex = /(https?:\/\/.*\.(?:mp4|mov|avi|wmv|flv|mkv|webm|ogg)|<video .*src=.*>)/i; // Video URL or HTML video

          if (!imageRegex.test(prBody) && !videoRegex.test(prBody)) {
            return {
              status: 'failure',
              message: 'Please include a screenshot or video in the PR description.',
            };
          } else {
            return {
              status: 'success',
              message: 'PR includes a screenshot or video in the description.',
            };
          }

    - name: Set PR status
      if: ${{ steps.pr-check.outputs.status == 'failure' }}
      uses: github-script@v6
      with:
        script: |
          github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.pull_request.head.sha,
            state: 'failure',
            context: 'Screenshot or Video Check',
            description: 'Please include a screenshot or video in the PR description.',
          });

    - name: Set PR status
      if: ${{ steps.pr-check.outputs.status == 'success' }}
      uses: github-script@v6
      with:
        script: |
          github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.pull_request.head.sha,
            state: 'success',
            context: 'Screenshot or Video Check',
            description: 'PR includes a screenshot or video in the description.',
          });
