name: Check PR for Screenshot or Video

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  check-pr-content:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR for image or video
        id: check-content
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "PR Body: $PR_BODY"

          imageRegex="!\[.*\]\(.*\)|<img .*src=.*>"
          videoRegex="(https?:\/\/.*\.(?:mp4|mov|avi|wmv|flv|mkv|webm|ogg)|<video .*src=.*)"

          if [[ -z "${PR_BODY// }" || ! "$PR_BODY" =~ $imageRegex && ! "$PR_BODY" =~ $videoRegex ]]; then
            echo "status=failure" >> $GITHUB_ENV
            echo "message=Please include a screenshot or video in the PR description." >> $GITHUB_ENV
          else
            echo "status=success" >> $GITHUB_ENV
            echo "message=PR includes a screenshot or video in the description." >> $GITHUB_ENV
          fi

      - name: Echo status
        if: always()
        run: |
          echo "Status: ${{ env.status }}"
          echo "Message: ${{ env.message }}"
          if [[ "${{ env.status }}" == "success" ]]; then
            exit 0  # Exit with success code
          else
            exit 1  # Exit with failure code
          fi
