name: Check Pull Request Flags

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, labeled, unlabeled]

jobs:
  check_flags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if YES or NO is checked
        run: |
          body="${{ github.event.pull_request.body }}"
          echo "Pull request body:"
          echo "$body"
          if echo "$body" | grep -q '\[\s*[xX]\s*\]\s*YES'; then
            echo "YES is checked."
            exit 0
          elif echo "$body" | grep -q '\[\s*[xX]\s*\]\s*NO'; then
            echo "NO is checked."
            exit 0
          else
            echo "Neither YES nor NO checkbox is checked."
            exit 1
          fi
